### ISSUE TITLE
Symbol’s function definition is void: split-and-follow-vertically

### ISSUE THREAD

**Issue by kosivantsov** [Zacalot/bible-mode#1]
This function is probably defined elsewhere, but it's not a part of my config, so splitting the window doesn't work

**Comment by Zacalot** [comment]
Whoops, it was a function in my own config, corrected now.

**Comment by kosivantsov** [comment]
Thank you, this one is fixed. But there are quite a few other functions not defined in this particular lisp file. Try using it in an uncustomized Emacs to see those bugs.

**Comment by Zacalot** [comment]
I believe it was because the file didn't require specific dependencies, it now appears to work fine on a clean config. Thanks for pointing this out.

**Comment by kosivantsov** [comment]
Thanks for fixing the issues! It works now. Great job!
