### ISSUE TITLE
How Install

### ISSUE THREAD

**Issue by eldrulo** [Zacalot/bible-mode#6]
How do I add/install this to emacs?

**Comment by Zacalot** [comment]
I added an example installation code snippet to the README
`(use-package bible-mode
  :straight (
             :host github
             :repo "Zacalot/bible-mode"))`

**Comment by eldrulo** [comment]
ty

**Comment by eldrulo** [comment]
Clone the Repository: First, you need to clone the bible-mode repository to a local directory. You can do this by opening a terminal and using the git command. If you have a specific directory where you keep Emacs packages, navigate there; otherwise, you can clone it into your home directory or any convenient location.

git clone https://github.com/Zacalot/bible-mode.git

Add the Directory to Your Emacs Load Path: Emacs needs to know where to find bible-mode. You do this by adding the directory to your Emacs load-path. Open your Emacs configuration file (usually ~/.emacs or ~/.emacs.d/init.el) and add the following lines, replacing path-to-bible-mode with the actual path where you cloned the repository.

(add-to-list 'load-path "path-to-bible-mode")

For example, if you cloned bible-mode into ~/emacs-packages/bible-mode, the line would be:

(add-to-list 'load-path "~/emacs-packages/bible-mode")

Require the Package: To ensure bible-mode is loaded when you start Emacs, add a line to require the package in your Emacs configuration file.


(require 'bible-mode)

Configure if Necessary: Depending on the package and your preferences, you might need to configure it further. For bible-mode, check its documentation (usually found in the README file within the repository or as comments in the .el files) for any additional setup or configuration options.

Restart Emacs: After saving your changes to the configuration file, restart Emacs to apply the changes.

Using bible-mode: With bible-mode installed, you should now be able to use its functionality. Check the package's documentation for how to use it, such as commands to open the Bible text, search, and other features.


This is what I did if helps anyone...
