### ISSUE TITLE
Reference Strong’s Concordance words in org-mode files as links

### ISSUE THREAD

**Issue by OrionRandD** [Zacalot/bible-mode#7]
Add this to your config file if you want to reference Strong’s Concordance words in org-mode files as links:

(org-link-set-parameters "hebrew+strong"
                         :follow #'bible-term-hebrew)
(org-link-set-parameters "greek+strong"
                         :follow #'bible-term-greek)

Can you give an example, using an org-file?

**Comment by Zacalot** [comment]
If you use a literate configuration file, you could install that behavior by putting this block in the file:

```
#+begin_src emacs-lisp
(org-link-set-parameters "hebrew+strong"
                         :follow #'bible-term-hebrew)
(org-link-set-parameters "greek+strong"
                         :follow #'bible-term-greek)
#+end_src
```

Then you can insert a link to a Hebrew or Greek concordance word with `C-c C-l` or `M-x org-insert-link` then typing "strong" to see either option, here are some examples of the resulted insertion:
```
[[hebrew+strong:0001]]
[[greek+strong:0001]]
```
Opening the link with `C-c C-o` or `M-x org-open-at-point` then opens a window pane with the concordance information.

I've now updated the README so this usage is more clear as well.
